function StereoSetup
%
% A stereo setup is represented by the following entities:
%
% LeftCamera        - complete internal description (see
%                     'help Camera' for details) of the left cam.
% RightCamera       - right cam.
% R                 - rotation of the right camera w.r.t. the left
%                     camera
% T                 - translation of the right camera w.r.t. the
%                     left camera
% FundamentalMatrix - F.Matrix describing the stereo setup
% Label             - alphanumeric label of the setup
%
% The following functions are available:
%
% StereoSetup_readFromCalibData    - initialise the stereo data
%                                    structure from a set of parameters
%                                    as generated by the Caltech Toolbox
% StereoSetup_computeFMatrix       - compute the fundamental matrix
% StereoSetup_reconstruct3D        - reconstruct points in 3D
%

%
% $Id: StereoSetup.m,v 1.1 2004/05/10 05:29:44 brandner Exp $
%
